language: objective-c
 
branches:
 only:
 - master
 
xcode_project: TayDD.xcodeproj
xcode_scheme: TayDDTests
xcode_sdk: iphonesimulator9.0 
osx_image: xcode7
 
script:
 - xcodebuild clean build -project TayDD.xcodeproj -scheme TayDDTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test

