language: objective-c
 
branches:
 only:
 - master
 
xcode_project: TayDD.xcodeproj
xcode_scheme: TayDDTests
xcode_sdk: iphonesimulator9.0 
 
script:
 - xcodebuild clean build -project TayDD.xcodeproj -scheme TayDDTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test
 - xcodebuild clean build -project TayDD.xcodeproj -scheme TayDDUITests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test

